name: 'Deploy Production to Server'

on:
  push:
    branches:
      - main


env:
    RELEASE_PATH: '/home/gabx/www/actions'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Cópia o código do github para a máquina do Workflow
            - name: Checkout Code
              uses: actions/checkout@v2
             
            - name: Transfer files to server
              uses: appleboy/scp-action@v0.1.3
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                source: '.'
                target: ${{ env.RELEASE_PATH }}/build

            - name: Install Dependencies
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                script: |
                    cd ${{ env.RELEASE_PATH }}/build
                    nvm use default
                    npm install

            - name: Start PM2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                script: |
                    cd ${{ env.RELEASE_PATH }}/build
                    nvm use default
                    pm2 delete -s "application" || :
                    pm2 start "npm run dev" --name "application"

            